DemoProject1/Controllers/CartController.cs
using DemoProject1.Data;
using DemoProject1.Models;
using DemoProject1.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoProject1.Controllers
{
    public class CartController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;

        public CartController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }


        public IActionResult GetCartItems()
        {
            List<CartItems> items = _db.CartItems.ToList();
            foreach(var item in items)
            {
                var product = _db.Products.Find(item.ProductId);
                item.Product.Id = product.Id;
            }

            return View(items);
        }


        public IActionResult AddInShoppingCart(int id)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == id);

            var existingProduct = _db.CartItems.FirstOrDefault(x => x.ProductId == product.Id);

            if(existingProduct == null)
            {
                CartItems cart = new CartItems()
                {
                    ProductId = product.Id,
                    Product = product,
                    Count = 1
                };

                _db.CartItems.Add(cart);
            }
            else
            {
                existingProduct.Count++;
            }

            _db.SaveChanges();

           

            var x = RedirectToAction("GetCartItems");
            return x;
        }


        public IActionResult RemoveCartItem(int id)
        {
            var obj = _db.CartItems.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.CartItems.Remove(obj);
            _db.SaveChanges();
            

            return this.RedirectToAction("GetCartItems");
        }

        //public ActionResult CartIcon()
        //{
        //    var temp = _db.CartItems.ToList().Count;
        //    BaseViewModel obj = new BaseViewModel()
        //    {
        //        ShoppingItemsCount = temp
        //    };
        //    return PartialView("_Layout", obj);
        //}

        public IActionResult PlaceOrder()
        {
            List<CartItems> items = _db.CartItems.ToList();

            List<OrderViewModel> orderList = new List<OrderViewModel>();

            foreach (var item in items)
            {
                var i = 1;
                var product = _db.Products.Find(item.ProductId);
                OrderViewModel obj = new OrderViewModel()
                {
                    SNo = i,
                    ProductName = product.Name,
                    Quantity = item.Count,
                    Price = product.Price,
                    Total = item.Count * product.Price
                };
                i++;
                orderList.Add(obj);
            }

            return View(orderList);
        }

    }
}

DemoProject1/Controllers/CategoryController.cs
using DemoProject1.Data;
using DemoProject1.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoProject1.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult GetList()
        {
            var items = _db.Category.ToList();
            return View(items);
        }

        // GET create 
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }

        // POST create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCategory(Category obj)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("GetList");
            }
            return View(obj);
        }


    }
}

DemoProject1/Views/Shared/_CartIcon.cshtml
@model DemoProject1.ViewModel.BaseViewModel

<div>@Model.ShoppingItemsCount</div>

DemoProject1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoProject1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoProject1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="GetList">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="GetCartItems">
                            <i class="fa fa-cart-plus" style="font-size:36px;color:cornflowerblue">&nbsp;</i>
                            <sup style="color:red; font-size:20px">2</sup> </a>
                            
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DemoProject1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>